// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1560336556);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 80);
user_pref("browser.startup.homepage_override.buildID", "20190530055249");
user_pref("browser.startup.homepage_override.mstone", "67.0.1");
user_pref("distribution.iniFile.exists.appversion", "67.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "67.0.1");
user_pref("extensions.lastPlatformVersion", "67.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"1f115c97-e6ce-4b53-8bbf-80260541dae4\",\"fxmonitor@mozilla.org\":\"04a2d974-a909-4515-a80f-41af9c24d838\",\"screenshots@mozilla.org\":\"4b2d33bc-446f-43cb-9a6b-5162ae356b4a\",\"webcompat-reporter@mozilla.org\":\"887d180e-4b88-424e-81b1-37923f92c122\",\"webcompat@mozilla.org\":\"15222e13-1c1f-47c3-bf1e-c6bb51f3da0f\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 58955);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "20cbab00-ac9c-4dbb-9c20-314d2310a00e");
user_pref("security.sandbox.plugin.tempDirSuffix", "7039eced-37ad-4670-8243-31720c1dd182");
user_pref("toolkit.telemetry.previousBuildID", "20190530055249");
